const equipment = {
 motor: {id:'MOT-102 / MOTOR ELÉCTRICO',name:'Motor de bomba #02',description:'Una variación en la vibración puede indicar que es momento de revisar el comportamiento del motor.',aLabel:'Vibración',a:'6,8',aUnit:'mm/s',bLabel:'Temperatura',b:'72',bUnit:'°C',status:'Precaución',tip:'Tendencia de vibración, condiciones de carga e historial de intervenciones.'},
 pump: {id:'BOM-204 / BOMBA CENTRÍFUGA',name:'Bomba de proceso #04',description:'La presión y la vibración ayudan a observar cambios en las condiciones de operación de la bomba.',aLabel:'Presión',a:'3,2',aUnit:'bar',bLabel:'Vibración',b:'2,1',bUnit:'mm/s',status:'Normal',tip:'Presión de operación, variaciones de caudal y registros de inspección.'},
 compressor: {id:'CMP-001 / COMPRESOR',name:'Compresor principal',description:'Un cambio térmico merece una revisión del contexto de operación y de las lecturas disponibles.',aLabel:'Temperatura',a:'91',aUnit:'°C',bLabel:'Presión',b:'7,4',bUnit:'bar',status:'Crítico',tip:'Tendencia térmica y condiciones de operación. El diagnóstico corresponde al personal técnico.'},
 belt: {id:'FAJ-008 / TRANSPORTADOR',name:'Faja transportadora #08',description:'El comportamiento del motor permite observar cambios en la carga de la línea de transporte.',aLabel:'Amperaje',a:'18,6',aUnit:'A',bLabel:'Temperatura',b:'46',bUnit:'°C',status:'Normal',tip:'Consumo eléctrico, condiciones de carga e historial del motor de accionamiento.'}
};
let selectedEquipment='motor';
const $ = selector => document.querySelector(selector);
document.querySelectorAll('[data-equipment]').forEach(button=>button.addEventListener('click',()=>{
 selectedEquipment=button.dataset.equipment;const data=equipment[selectedEquipment];
 document.querySelectorAll('[data-equipment]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});
 $('#equipment-id').textContent=data.id;$('#equipment-title').textContent=data.name;$('#equipment-description').textContent=data.description;$('#equipment-tip').textContent=data.tip;
 $('#equipment-status').textContent=data.status;$('#equipment-status').className='status '+(data.status==='Normal'?'normal':'warning');
 if(data.status==='Crítico'){$('#equipment-status').style.background='#fee2e2';$('#equipment-status').style.color='#b91c1c';}else{$('#equipment-status').removeAttribute('style');}
 for(const s of ['a','b']){$('#sensor-'+s+'-label').textContent=data[s+'Label'];const value=$('#sensor-'+s);value.replaceChildren(document.createTextNode(data[s]+' '));const unit=document.createElement('small');unit.textContent=data[s+'Unit'];value.append(unit);}
 $('.machine-visual svg').setAttribute('aria-label','Esquema conceptual de motor de accionamiento para '+data.name);
}));
const roles={manager:{eyebrow:'PLANIFICACIÓN Y CONTROL',title:'Decide con la planta a la vista.',description:'Centraliza el estado de los activos y organiza las intervenciones según su prioridad.',list:['Consultar activos y alertas por criticidad.','Asignar responsables a las órdenes de trabajo.','Revisar el historial para planificar intervenciones.'],example:'Al iniciar el turno, revisa las alertas pendientes y distribuye las intervenciones del día.'},technician:{eyebrow:'EJECUCIÓN Y TRAZABILIDAD',title:'Llega a cada intervención con contexto.',description:'Consulta el equipo, la alerta y los antecedentes antes de registrar el trabajo realizado.',list:['Revisar el detalle de la orden asignada.','Consultar el historial y las lecturas del activo.','Registrar acciones y evidencias de la intervención.'],example:'Antes de intervenir el motor, consulta la alerta que originó la orden y registra el resultado de la revisión.'},operator:{eyebrow:'VISIBILIDAD A PIE DE PLANTA',title:'Comprende el estado de un vistazo.',description:'Una lectura clara del estado de los equipos facilita comunicar una condición que requiere atención.',list:['Identificar estados normales, de precaución y críticos.','Consultar la información del equipo.','Comunicar anomalías al equipo de mantenimiento.'],example:'Durante el turno, identifica un cambio de estado y comunica la situación siguiendo el procedimiento de la planta.'}};
document.querySelectorAll('[data-role]').forEach(button=>button.addEventListener('click',()=>{const data=roles[button.dataset.role];document.querySelectorAll('[data-role]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});for(const field of ['eyebrow','title','description','example'])$('#role-'+field).textContent=data[field];$('#role-list').replaceChildren(...data.list.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));}));
const scenarioSteps=[{symbol:'⌁',title:'Una lectura merece atención',text:'Observa la variable y su tendencia antes de interpretar una desviación. Los valores de esta demo son ficticios y no definen límites seguros.'},{symbol:'◎',title:'Revisa antes de confirmar',text:'Contrasta el historial, la calidad del sensor y las condiciones de operación. Una alerta es un punto de partida para la revisión técnica, no un diagnóstico.'},{symbol:'✓',title:'Coordina el siguiente paso',text:'Tras la validación técnica, el equipo puede organizar una orden, asignar un responsable y registrar la intervención. En esta demo no se crea ninguna orden real.'}];
let scenarioStep=0;const scenarioDialog=$('#scenario-dialog');
function renderScenario(){const step=scenarioSteps[scenarioStep];for(const field of ['symbol','title','text'])$('#scenario-'+field).textContent=step[field];document.querySelectorAll('.scenario-progress span').forEach((s,i)=>{s.classList.toggle('current',i===scenarioStep);if(i===scenarioStep)s.setAttribute('aria-current','step');else s.removeAttribute('aria-current');});$('#scenario-back').disabled=scenarioStep===0;$('#scenario-next').textContent=scenarioStep===2?'Finalizar recorrido ✓':'Continuar →';}
$('#open-scenario').addEventListener('click',()=>{scenarioStep=0;$('#scenario-asset').textContent=equipment[selectedEquipment].name;renderScenario();scenarioDialog.showModal();});$('#close-scenario').addEventListener('click',()=>scenarioDialog.close());$('#scenario-back').addEventListener('click',()=>{scenarioStep=Math.max(0,scenarioStep-1);renderScenario();});$('#scenario-next').addEventListener('click',()=>{if(scenarioStep===2){scenarioDialog.close();return;}scenarioStep++;renderScenario();});
function updatePilot(){const count=$('#pilot-count').value;$('#pilot-count-label').textContent=count;$('#pilot-total').textContent=count;$('#pilot-summary-text').textContent=$('#pilot-sector').value+' · '+$('#pilot-priority').value;}
$('#pilot-form').addEventListener('input',updatePilot);$('#pilot-form').addEventListener('change',updatePilot);
$('#pilot-form').addEventListener('submit',event=>{event.preventDefault();const content=['PREDICTIVEMAINTAIN — RESUMEN DE PILOTO','Propuesta ilustrativa de planificación','',`Operación: ${$('#pilot-sector').value}`,`Activos: ${$('#pilot-count').value}`,`Objetivo: ${$('#pilot-priority').value}`,'','1. Seleccionar activos críticos y responsables.','2. Revisar sensores, calidad de datos y conectividad.','3. Definir umbrales con el equipo técnico.','4. Acordar criterios de validación y observar resultados.','','No es una cotización ni una evaluación técnica. No se ha enviado información ni creado una cuenta.','Proyecto: https://github.com/PredictiveTech'].join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='predictivemaintain-resumen-piloto.txt';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
